export let mime_to_ext = {
  'audio/mp4': 'm4a',
  'audio/mpeg': 'mp3',
  'audio/vnd.wave': 'wav',
  'audio/ogg': 'ogg',
  'audio/midi': 'mid',
  'video/vnd.avi': 'avi',
  'video/quicktime': 'mov',
  'video/x-matroska': 'mkv',
  'video/3gpp': '3gp',
  'video/mpeg': 'mpeg',
  'video/mp4': 'mp4',
  'application/json': 'json',
  'application/xhtml+xml': 'xhtml',
  'application/vnd.ms-powerpoint': 'ppt',
  'application/vnd.ms-excel': 'xls',
  'application/octet-stream': 'bin',
  'image/jpeg': 'jpg',
  'image/bmp': 'bmp',
  'text/plain': 'txt',
  'text/html': 'html',
  'text/markdown': 'md',
  'text/javascript': 'js',
  'text/coffeescript': 'coffee',
  'text/calendar': 'ics',
  'text/x-asm': 'asm',
  'text/x-pascal': 'pas',
}
